from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set
from datetime import datetime
from communication.messages.action_message import ActionMessage
from communication.messages.observation_packet import AgentStatus, BondStatus


@dataclass
class Bond:
    """A bond between agents that generates sparks"""
    bond_id: str
    members: Set[str]  # Set of agent_ids
    leader_id: str
    mission_id: Optional[str]  # None if no active mission
    sparks_generated_this_tick: int = 0


@dataclass
class Mission:
    """A collaborative mission for bonded agents"""
    mission_id: str
    bond_id: str
    title: str
    description: str
    goal: str
    current_progress: str
    leader_id: str
    assigned_tasks: Dict[str, str]  # agent_id -> task
    is_complete: bool = False
    created_tick: int = 0


@dataclass
class Agent:
    """Complete agent entity"""
    agent_id: str
    name: str
    species: str
    personality: List[str]
    quirk: str
    ability: str
    age: int
    sparks: int
    status: AgentStatus
    bond_status: BondStatus
    bond_members: List[str]
    home_realm: str
    backstory: str
    opening_goal: str


@dataclass
class WorldState:
    """
    The complete state of the Spark-World simulation.
    
    This is the central data structure that contains everything needed to run
    the simulation and generate observation packets for agents.
    
    Attributes:
        tick: Current simulation tick number
        is_running: Whether the simulation is currently running
        agents: All agents in the world, indexed by agent_id
        bonds: All bonds in the world, indexed by bond_id
        missions: All active missions, indexed by mission_id
        bob_sparks: Bob's current spark count
        bob_sparks_per_tick: How many sparks Bob gains per tick
        pending_actions: Actions waiting to be processed this tick
        message_queue: Messages waiting to be delivered to agents
        events_this_tick: Raw events for Storyteller processing
        agents_vanished_this_tick: Agents that vanished this tick
        agents_spawned_this_tick: Agents that spawned this tick
        bonds_formed_this_tick: Bonds that formed this tick
        bonds_dissolved_this_tick: Bonds that dissolved this tick
        current_processing_stage: Current stage of the 6-stage tick
        mission_meetings_in_progress: Whether mission meetings are happening
        total_sparks_minted: Total sparks generated by bonds
        total_sparks_lost: Total sparks lost to upkeep
        total_raids_attempted: Total raid attempts
        total_bonds_formed: Total bonds formed
    """
    # Simulation Control
    tick: int = 0
    is_running: bool = True
    
    # Core Entities
    agents: Dict[str, Agent] = field(default_factory=dict)
    bonds: Dict[str, Bond] = field(default_factory=dict)
    missions: Dict[str, Mission] = field(default_factory=dict)
    
    # Game Mechanics State
    bob_sparks: int = 100  # Bob's current spark count
    bob_sparks_per_tick: int = 5  # How many Bob gains per tick
    
    # Communication Queues
    pending_actions: List[ActionMessage] = field(default_factory=list)
    message_queue: Dict[str, List[ActionMessage]] = field(default_factory=dict)  # agent_id -> messages
    
    # Event Tracking
    events_this_tick: List[Dict] = field(default_factory=list)  # Raw events for Storyteller
    agents_vanished_this_tick: List[str] = field(default_factory=list)
    agents_spawned_this_tick: List[str] = field(default_factory=list)
    bonds_formed_this_tick: List[str] = field(default_factory=list)
    bonds_dissolved_this_tick: List[str] = field(default_factory=list)
    
    # Processing State
    current_processing_stage: str = "idle"  # Current stage of the 6-stage tick
    mission_meetings_in_progress: bool = False
    
    # Statistics
    total_sparks_minted: int = 0
    total_sparks_lost: int = 0
    total_raids_attempted: int = 0
    total_bonds_formed: int = 0 